import org.junit.jupiter.api.*;
import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.*;

import static org.junit.jupiter.api.Assertions.*;
import java.io.*;

class MainTest {
    @ParameterizedTest(name = "{index} Typechecking well-typed program {0}")
    @ValueSource(strings = {
            "tests/ascriptions/well-typed/good-anonymous-function.stella",
            "tests/ascriptions/well-typed/good-pair.stella",
            "tests/exceptions/well-typed/panic-1.stella",
            "tests/exceptions/well-typed/panic-2.stella",
            "tests/exceptions/well-typed/panic-3.stella",
            "tests/exceptions/well-typed/throw-1.stella",
            "tests/exceptions/well-typed/throw-2.stella",
            "tests/exceptions/well-typed/try-catch-1.stella",
            "tests/exceptions/well-typed/try-catch-2.stella",
            "tests/exceptions/well-typed/try-with-1.stella",
            "tests/exceptions/well-typed/try-with-2.stella",
            "tests/let-bindings/well-typed/let-1.stella",
            "tests/let-bindings/well-typed/let-2.stella",
            "tests/let-bindings/well-typed/let-3.stella",
            "tests/let-bindings/well-typed/let-4.stella",
            "tests/letrecs/well-typed/letrec.stella",
            "tests/lists/well-typed/empty-list.stella",
            "tests/lists/well-typed/lists-1.stella",
            "tests/lists/well-typed/lists-2.stella",
            "tests/lists/well-typed/lists-3.stella",
            "tests/recursions/well-typed/fix-2.stella",
            "tests/recursions/well-typed/fix.stella",
            "tests/recursions/well-typed/general-recursion.stella",
            "tests/references/well-typed/refs-1.stella",
            "tests/references/well-typed/refs-2.stella",
            "tests/references/well-typed/refs-3.stella",
            "tests/references/well-typed/refs-4.stella",
            "tests/sum-types/well-typed/sum-types-1.stella",
            "tests/sum-types/well-typed/sum-types-2.stella",
            "tests/sum-types/well-typed/sum-types-3.stella",
            "tests/tuples/well-typed/tuples-1.stella",
            "tests/typealiases/well-typed/double-alias.stella",
            "tests/typealiases/well-typed/simple-alias.stella",
            "tests/units/well-typed/ignore.stella",
            "tests/units/well-typed/test-1.stella",
            "tests/units/well-typed/test-2.stella",
            "tests/variants/nullary/well-typed/nullary-1.stella",
            "tests/variants/nullary/well-typed/nullary-2.stella",
            "tests/variants/nullary/well-typed/nullary-3.stella",
            "tests/variants/nullary/well-typed/nullary-4.stella",
            "tests/variants/well-typed/variants-1.stella",
            "tests/variants/well-typed/variants-2.stella",
            "tests/variants/well-typed/variants-3.stella",
    })
    void testWellTyped(String filepath) throws Exception {
        String[] args = new String[0];
        final InputStream original = System.in;
        final FileInputStream fips = new FileInputStream(filepath);
        System.setIn(fips);
        Assertions.assertDoesNotThrow(() -> Main.main(args));
        System.setIn(original);
    }

    @ParameterizedTest(name = "{index} Typechecking ill-typed program {0}")
    @ValueSource(strings = {
            "tests/ascriptions/ill-typed/bad-anonymous-function.stella",
            "tests/ascriptions/ill-typed/bad-pair.stella",
            "tests/exceptions/ill-typed/ambiguous-panic-type-1.stella",
            "tests/exceptions/ill-typed/ambiguous-panic-type-2.stella",
            "tests/exceptions/ill-typed/ambiguous-panic-type-3.stella",
            "tests/exceptions/ill-typed/ambiguous-panic-type-4.stella",
            "tests/exceptions/ill-typed/ambiguous-throw-type-1.stella",
            "tests/exceptions/ill-typed/ambiguous-throw-type-2.stella",
            "tests/exceptions/ill-typed/ambiguous-throw-type-3.stella",
            "tests/exceptions/ill-typed/exception-type-not-declared-throw.stella",
            "tests/exceptions/ill-typed/exception-type-not-declared-try-catch.stella",
            "tests/exceptions/ill-typed/exception-type-not-declared-try-with.stella",
            "tests/exceptions/ill-typed/unexpected-type-for-expression-throw-1.stella",
            "tests/exceptions/ill-typed/unexpected-type-for-expression-throw-2.stella",
            "tests/exceptions/ill-typed/unexpected-type-for-expression-try-catch-1.stella",
            "tests/exceptions/ill-typed/unexpected-type-for-expression-try-catch-2.stella",
            "tests/exceptions/ill-typed/unexpected-type-for-expression-try-with-1.stella",
            "tests/exceptions/ill-typed/unexpected-type-for-expression-try-with-2.stella",
            "tests/let-bindings/ill-typed/bad-let-1.stella",
            "tests/let-bindings/ill-typed/bad-let-2.stella",
            "tests/let-bindings/ill-typed/bad-let-3.stella",
            "tests/let-bindings/ill-typed/bad-let-4.stella",
            "tests/let-bindings/ill-typed/bad-let-5.stella",
            "tests/let-bindings/ill-typed/bad-let-6.stella",
            "tests/let-bindings/ill-typed/bad-let-7.stella",
            "tests/letrecs/ill-typed/bad-letrec.stella",
            "tests/lists/ill-typed/ambiguous-list-type-isempty.stella",
            "tests/lists/ill-typed/bad-lists-1.stella",
            "tests/lists/ill-typed/bad-lists-2.stella",
            "tests/lists/ill-typed/bad-variants-1.stella",
            "tests/lists/ill-typed/not-a-list-head.stella",
            "tests/lists/ill-typed/not-a-list-isempty.stella",
            "tests/lists/ill-typed/not-a-list-tail.stella",
            "tests/lists/ill-typed/unexepected-list-unit.stella",
            "tests/lists/ill-typed/unexpected-empty-list.stella",
            "tests/lists/ill-typed/unexpected-list-if-condition.stella",
            "tests/lists/ill-typed/unexpected-list-let-bindings.stella",
            "tests/lists/ill-typed/unexpected-list-natrec.stella",
            "tests/lists/ill-typed/unexpected-list-pair.stella",
            "tests/recursions/ill-typed/divergent-param-and-return-types.stella",
            "tests/recursions/ill-typed/fix-2.stella",
            "tests/recursions/ill-typed/fix.stella",
            "tests/recursions/ill-typed/general-recursion.stella",
            "tests/recursions/ill-typed/not-a-function.stella",
            "tests/recursions/ill-typed/two-parameters.stella",
            "tests/references/ill-typed/ambiguous-reference-type-1.stella",
            "tests/references/ill-typed/not-a-reference-1.stella",
            "tests/references/ill-typed/not-a-reference-2.stella",
            "tests/references/ill-typed/not-a-reference-3.stella",
            "tests/references/ill-typed/not-a-reference-4.stella",
            "tests/references/ill-typed/not-a-reference-5.stella",
            "tests/references/ill-typed/unexpected-memory-address-1.stella",
            "tests/references/ill-typed/unexpected-memory-address-2.stella",
            "tests/references/ill-typed/unexpected-memory-address-3.stella",
            "tests/references/ill-typed/unexpected-memory-address-4.stella",
            "tests/references/ill-typed/unexpected-type-for-expression-1.stella",
            "tests/references/ill-typed/unexpected-type-for-expression-2.stella",
            "tests/references/ill-typed/unexpected-type-for-expression-3.stella",
            "tests/references/ill-typed/unexpected-type-for-expression-4.stella",
            "tests/sum-types/ill-typed/bad-sum-types-1.stella",
            "tests/sum-types/ill-typed/bad-sum-types-10.stella",
            "tests/sum-types/ill-typed/bad-sum-types-11.stella",
            "tests/sum-types/ill-typed/bad-sum-types-12.stella",
            "tests/sum-types/ill-typed/bad-sum-types-13.stella",
            "tests/sum-types/ill-typed/bad-sum-types-2.stella",
            "tests/sum-types/ill-typed/bad-sum-types-3.stella",
            "tests/sum-types/ill-typed/bad-sum-types-4.stella",
            "tests/sum-types/ill-typed/bad-sum-types-5.stella",
            "tests/sum-types/ill-typed/bad-sum-types-6.stella",
            "tests/sum-types/ill-typed/bad-sum-types-7.stella",
            "tests/sum-types/ill-typed/bad-sum-types-8.stella",
            "tests/sum-types/ill-typed/bad-sum-types-9.stella",
            "tests/tuples/ill-typed/bad-tuples-1.stella",
            "tests/tuples/ill-typed/bad-tuples-2.stella",
            "tests/tuples/ill-typed/bad-tuples-3.stella",
            "tests/typealiases/ill-typed/wrong-double-alias.stella",
            "tests/typealiases/ill-typed/wrong-simple-alias.stella",
            "tests/units/ill-typed/bad_ignore.stella",
            "tests/units/ill-typed/test-1.stella",
            "tests/units/ill-typed/test-2.stella",
            "tests/units/ill-typed/test-3.stella",
            "tests/variants/ill-typed/ambiguous-variant-type-1.stella",
            "tests/variants/ill-typed/ambiguous-variant-type-2.stella",
            "tests/variants/ill-typed/ambiguous-variant-type-3.stella",
            "tests/variants/ill-typed/non-exaustive-match-patterns-1.stella",
            "tests/variants/ill-typed/undefined-variable-1.stella",
            "tests/variants/ill-typed/unexpected-pattern-match-1.stella",
            "tests/variants/ill-typed/unexpected-pattern-match-2.stella",
            "tests/variants/ill-typed/unexpected-type-of-expression-1.stella",
            "tests/variants/ill-typed/unexpected-type-of-expression-2.stella",
            "tests/variants/ill-typed/unexpected-type-of-expression-3.stella",
            "tests/variants/ill-typed/unexpected-type-of-expression-4.stella",
            "tests/variants/ill-typed/unexpected-type-of-expression-with-alternative-errors.stella",
            "tests/variants/ill-typed/unexpected-variable-label-1.stella",
            "tests/variants/ill-typed/unexpected-variable-label-2.stella",
            "tests/variants/ill-typed/unexpected-variant-1.stella",
            "tests/variants/ill-typed/unexpected-variant-2.stella",
            "tests/variants/ill-typed/unexpected-variant-3.stella",
            "tests/variants/nullary/ill-typed/missing_data_for_label.stella",
            "tests/variants/nullary/ill-typed/non_nullary_var_pattern.stella",
            "tests/variants/nullary/ill-typed/nullary_var_pattern.stella",
            "tests/variants/nullary/ill-typed/unexpecteed_data_nullary.stella",
    })
    void testIllTyped(String filepath) throws Exception {
        String[] args = new String[0];
        final FileInputStream fips = new FileInputStream(filepath);
        System.setIn(fips);

        Exception exception = assertThrows(Exception.class, () -> Main.main(args), "Expected the type checker to fail!");
        System.out.println("Type Error: " + exception.getMessage());
    }
}
